version: "3.1"

language: en

recipe: default.v1

assistant_id: health_assistant_bot

pipeline:

  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer

  - name: CountVectorsFeaturizer

  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 5

  - name: DIETClassifier
    epochs: 200
    constrain_similarities: True

  - name: EntitySynonymMapper

  - name: ResponseSelector
    epochs: 60

  - name: FallbackClassifier
    threshold: 0.4
    ambiguity_threshold: 0.1

policies:

  - name: RulePolicy

  - name: MemoizationPolicy
    max_history: 5

  - name: TEDPolicy
    epochs: 100
    max_history: 5
    constrain_similarities: True
